version: "3"
services:
  bmenu-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: server
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - bmenu-db
  client:
    build: client
    ports:
      - "5173:5173"
    volumes:
      - .:/client
    env_file:
      .env
    command: bash -c "npm run dev -- --host"
    depends_on:
      - server
volumes:
  db_data: